name: Doxygen GitHub Pages Deploy Action

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - run: mkdir doxygen/Docs/
    - uses: mattnotmitt/doxygen-action@v1.9.5
      with:
        working-directory: 'doxygen/Docs/'
        doxyfile-path: 'doxygen/Doxyfile'
        enable-latex: true      